import turtle
turtle.color("green")
turtle.forward(100)
turtle.right(45)
turtle.color('blue')
turtle.forward(50)
turtle.right(90)
turtle.color('black')
turtle.forward(100)

turtle.color("green")
turtle.forward(100)
turtle.right(45)
turtle.color('blue')
turtle.forward(50)
turtle.right(90)
turtle.color('black')
turtle.forward(100)